name: Cloudflare Pages Deployment Cleaner

on:
  push:
    branches:
      - main

jobs:
  delete-old-deployments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Call Cloudflare Pages API
      env:
        ENDPOINT: https://api.cloudflare.com/client/v4/accounts/${{ secrets.ACCOUNT_ID }}/pages/projects/${{ secrets.PROJECT_NAME }}/deployments
      run: |
        RESPONSE=$(curl -s -X GET $ENDPOINT -H 'Authorization: Bearer ${{ secrets.API_TOKEN }}')
        CURRENT_DATE=$(date +%s)
        DATE_AFTER_SUBTRACTING_DAYS=$(($CURRENT_DATE - (${{ secrets.EXPIRATION_DAYS }} * 60)))
        FORMATTED_DATE=$(date -u -d @$DATE_AFTER_SUBTRACTING_DAYS +'%Y-%m-%dT%H:%M:%SZ')
        DEPLOYMENTS=$(echo $RESPONSE | jq -r --arg DATE $FORMATTED_DATE '.result[] | select(.created_on < $DATE)')
        echo $DEPLOYMENTS | while IFS= read -r SINGLE_DEPLOY; do
          DEPLOY_ID=$(echo $SINGLE_DEPLOY | jq -r '.id')
          curl -X DELETE \
          -H 'Content-Type: application/json;charset=UTF-8' \
          -H 'Authorization: Bearer ${{ secrets.API_TOKEN }}' \
          '$ENDPOINT/$DEPLOY_ID'
          echo 'Deleted deployment ->  $DEPLOY_ID'
        done
