name: Cloudflare Pages Deployment Cleaner

on:
  push:
    branches:
      - main

jobs:
  delete-old-deployments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Delete old deployments
      env:
        ENDPOINT: https://api.cloudflare.com/client/v4/accounts/${{ secrets.ACCOUNT_ID }}/pages/projects/${{ secrets.PROJECT_NAME }}/deployments
        API_TOKEN: "Authorization: Bearer '${{ secrets.API_TOKEN }}'"
        EXPIRATION_DAYS: ${{ secrets.EXPIRATION_DAYS }}
      run: |
        RESPONSE=$(curl -s -w '\n%{http_code}' -X GET $ENDPOINT \
              -H $API_TOKEN
        STATUS=$(echo $RESPONSE | tail -n1)
        OUTPUT=$(echo $RESPONSE | sed '$d')
        if [ $STATUS -eq 200 ]; then
          echo 'API call successful'
          echo $OUTPUT
        else
          echo $STATUS
        fi
