name: Cloudflare Pages Deployment Cleaner

on:
  push:
    branches:
      - main

jobs:
  delete-old-deployments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Call Cloudflare Pages API
      env:
        ENDPOINT: https://api.cloudflare.com/client/v4/accounts/${{ secrets.ACCOUNT_ID }}/pages/projects/${{ secrets.PROJECT_NAME }}/deployments
      run: |
        RESPONSE=$(curl -s -w '\n%{http_code}' -X GET $ENDPOINT \
              -H 'Authorization: Bearer ${{ secrets.API_TOKEN }}')
        
        echo $(echo $RESPONSE | jq --arg exp_days '${{ secrets.EXPIRATION_DAYS }}' -r '.result[] | select(((now - (strptime("%Y-%m-%dT%H:%M:%SZ"; .created_on) | mktime)) / 86400) > ($exp_days | tonumber))')

        DEPLOYMENTS=$(echo $RESPONSE | jq --arg exp_days '${{ secrets.EXPIRATION_DAYS }}' -r '.result[] | select(((now - (strptime("%Y-%m-%dT%H:%M:%SZ"; .created_on) | mktime)) / 86400) > ($exp_days | tonumber))')
          while IFS= read -r SINGLE_DEPLOY; do
            DEPLOY_ID=$(echo $SINGLE_DEPLOY | jq -r '.id')
            curl -X DELETE '$ENDPOINT/$DEPLOY_ID' -H 'Authorization: Bearer ${{ secrets.API_TOKEN }}'
