name: Cloudflare Pages Deployment Cleaner

on:
  push:
    branches:
      - main

env:
    ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
    PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
    EXPIRATION_DAYS: ${{ secrets.EXPIRATION_DAYS }}
    API_TOKEN: ${{ secrets.API_TOKEN }}
jobs:
  delete-old-deployments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Delete old deployments
      run: |
        echo https://api.cloudflare.com/client/v4/accounts/${{ env.ACCOUNT_ID }}/pages/projects/${{ env.PROJECT_NAME }}/deployments
