name: Delete old deployments

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.17.1'
    - name: Install dependencies
      run: npm install
    - name: Run script
      run: node cloudfare.js
