name: Clean Old CloudFlare Pages Deployments

on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Trigger the workflow manually'
        default: 'true'
jobs:
  delete-old-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call Cloudflare Pages API
        env:
          ENDPOINT: https://api.cloudflare.com/client/v4/accounts/${{ secrets.ACCOUNT_ID }}/pages/projects/${{ secrets.PROJECT_NAME }}/deployments
        run: |
          response=$(curl -s -X GET $ENDPOINT -H 'Authorization: Bearer ${{ secrets.API_TOKEN }}')
          currentDate=$(date +%s)
          cutoffDate=$(($currentDate - (${{ secrets.EXPIRATION_DAYS }} * 60)))
          echo $response | jq -c '.result[]' | while read obj; do
            createdTime=$(echo $obj | jq -r '.created_on')
            epochTime=$(date -u -d $createdTime +%s)            
            if [ "${epochTime}" -lt "${cutoffDate}" ]; then
                deploymentId=$(echo $obj | jq -r '.id')
                echo "Deployment -> $obj"
            fi
          done
