name: Cloudflare Pages Deployment Cleaner

on:
  push:
    branches:
      - main

jobs:
  delete-old-deployments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Delete old deployments
      run: |
        endpoint="https://api.cloudflare.com/client/v4/accounts/${{ secrets.ACCOUNT_ID }}/pages/projects/${{ secrets.PROJECT_NAME }}/deployments"
        expirationDays=7
        apiToken="${{ secrets.API_TOKEN }}"
        headers=(
          "Content-Type: application/json;charset=UTF-8"
          "Authorization: Bearer ${apiToken}"
        )
        echo "${deployments}" | jq '.result[]'
        deployments=$(curl -sSL -H "${headers[0]}" -H "${headers[1]}" "${endpoint}")
        for deployment in $(echo "${deployments}" | jq -c '.result[]'); do
          if [[ $(($(date +%s) - $(date -d $(echo "${deployment}" | jq -r '.created_on') +%s))) -gt $((${expirationDays} * 86400)) ]]; then
            deploymentId=$(echo "${deployment}" | jq -r '.id')
            curl -sSL -X DELETE -H "${headers[0]}" -H "${headers[1]}" "${endpoint}/${deploymentId}"
          fi
        done
