name: Delete old Cloudflare deployments

on:
  push:
    branches:
      - main

jobs:
  delete_deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          node -e "$(cat <<EOF
          const endpoint = 'https://api.cloudflare.com/client/v4/accounts/${{ secrets.ACCOUNT_ID }}/pages/projects/${{ secrets.PROJECT_NAME }}/deployments';
          const expirationDays = 7;

          (async () => {
            const init = {
              headers: {
                'Content-Type': 'application/json;charset=UTF-8',
                'Authorization': ${{ secrets.API_TOKEN }},
              },
            };

            const response = await fetch(endpoint, init);
            const deployments = await response.json();

            for (const deployment of deployments.result) {
              if ((Date.now() - new Date(deployment.created_on)) / 86400000 > expirationDays) {
                await fetch(\`\${endpoint}/\${deployment.id}\`, {
                  method: 'DELETE',
                  headers: {
                    'Content-Type': 'application/json;charset=UTF-8',
                    'Authorization': ${{ secrets.API_TOKEN }},
                  },
                });
              }
            }
          })().catch(console.error);
          EOF
          )"
