name: Cloudflare Pages Deployment Cleaner

on:
  push:
    branches:
      - main

jobs:
  delete-old-deployments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Delete old deployments
      env:
        ENDPOINT: https://api.cloudflare.com/client/v4/accounts/${{ secrets.ACCOUNT_ID }}/pages/projects/${{ secrets.PROJECT_NAME }}/deployments"
        EXPIRATION_DAYS: ${{ secrets.EXPIRATION_DAYS }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        echo $ENDPOINT
        echo $EXPIRATION_DAYS
        echo $API_TOKEN
